require(ggplot2)
t1 <- read.table("all_withMIN.tsv", head = T, sep = "\t")
ggplot(t1) + geom_point(aes(x = mean, y = 2^MIN, col = pool))
ggsave("2^MIN.png")
ggplot(t1) + geom_point(aes(x = mean, y = MIN, col = pool))
ggsave("MIN.png")
ggplot(t1) + geom_point(aes(x = mean, y = var/mean, col = pool))
ggsave("fano.png")
ggplot(t1) + geom_point(aes(x = mean, y = var/(mean^2), col = pool))
ggsave("cvsquared.png")
ggplot(t1) + geom_point(aes(x = mean_z, y = var_z, col = pool), alpha = 0.5)
ggsave("zvar_vs_zmean.png")
ggplot(t1) + geom_point(aes(x = mean_z, y = fano_z, col = pool), alpha = 0.5)
ggsave("zfano_vs_zmean.png")
ggplot(t1) + geom_point(aes(x = mean_z, y = cv2_z, col = pool), alpha = 0.5)
ggsave("zcv2_vs_zmean.png")
